from enum import Enum


class DANGER_SCORE(Enum):
    ONESTAR = "ONESTAR"  # LIGHT
    TWOSTAR = "TWOSTAR"  # LOW
    THREESTAR = "THREESTAR"  # MEDIUM
    FOURSTAR = "FOURSTAR"  # HIGH
    FIVESTAR = "FIVESTAR"  # EXTREME
